# Generated by Django 3.2 on 2021-04-20 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminn',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Admin', serialize=False, to='classroom.user')),
                ('name', models.CharField(max_length=250)),
                ('roll_no', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
