# Generated by Django 3.2 on 2021-04-29 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_remove_adminn_roll_no'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagetoteacher',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='messagetoteacher',
            name='student',
        ),
        migrations.RemoveField(
            model_name='messagetoteacher',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='ClassNotice',
        ),
        migrations.DeleteModel(
            name='MessageToTeacher',
        ),
    ]
