# Generated by Django 3.2 on 2021-04-29 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20210429_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_profile_pic',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_profile_pic',
        ),
    ]
