# Generated by Django 3.2 on 2021-06-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_auto_20210622_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='enddate',
            field=models.DateField(help_text='coming back on ...', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='startdate',
            field=models.DateField(help_text='leave start date is on ..', null=True, verbose_name='Start Date'),
        ),
    ]
